project:
  type: website
  output-dir: docs

website:
  title: "kylienewcomer.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd

format:
  html:
    theme: Solar
    css: styles.css
    toc: true



