project:
  type: website
  output-dir: docs
execute:
  freeze: auto
  
website:
  title: "Kylie Newcomer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd

format:
  html:
    theme: Solar
    css: styles.css
    toc: true



